ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'teal';
ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'ocean';
ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'grape';
ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'berry';
ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'coffee';
ALTER TYPE "ThemeId" ADD VALUE IF NOT EXISTS 'rose';
